language: node_js
node_js:
- '0.10'
notifications:
  email:
    recipients:
    - martinmicunda@hotmail.com
    on_success: never
    on_failure: always
env:
  global:
  - secure: IndJScC1KSZ7Cc1XohiKiwaCnQFLT02DBaliSLpFHpD6rrcI3P+bw4VmqpzqvnH7jCaYFCGudqzgKtdZgF0mNJ2Uo7VKzybiPtNUx4jpgowG0bJPCLqkBOVkQJUOkX1hmFdletQRIlcCTgsnXihD42pmTZnDsfxC+0h2FUmJSc0=
  - secure: DMW803T7RWE25ldhX73E/tqSWAZMaGUsd1dUbcxmXnU7OxpDPRSej2qtFJFHaYQi1inIL6zaKWD7Q5Mt6U5iueNvKtuDEabwjHw1Q2iwH/jLOKf0AtVvpQQJTBSIAzCDdqKTIwAnkFc5qRUuB1hphlrRhu7DVVZCVHZfuMIpAWI=
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install -g grunt-cli@0.1.x karma@0.10.x protractor@0.14.x
- npm install --quiet
before_script:
- curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
- node app.js &
- sleep 3
script:
- grunt test:unit
deploy:
  provider: heroku
  app: tweet-map
  api_key:
    secure: ! "ORLh6OeTVqwzxHJGN/czBVAXRf2S64oO3Beo+st6f9Qd8qxaO6w2T7khxHVhYEiG+/ihoi2A5FaD7CkfuKRNoxTCNjkGEGZKNXV5fnAdd+GMKQLloODid/9CdnxWdX3mJrKe03SsUInl4I241Jfl+zHhmFl/Tg+f6z03GC9zFdc="
