language: node_js
node_js:
  - "0.10"

notifications:
  email:
    recipients:
      - martinmicunda@hotmail.com
    on_success: never
    on_failure: always

# set sauce labs credentials
env:
  global:
    - secure: 'IndJScC1KSZ7Cc1XohiKiwaCnQFLT02DBaliSLpFHpD6rrcI3P+bw4VmqpzqvnH7jCaYFCGudqzgKtdZgF0mNJ2Uo7VKzybiPtNUx4jpgowG0bJPCLqkBOVkQJUOkX1hmFdletQRIlcCTgsnXihD42pmTZnDsfxC+0h2FUmJSc0='
    - secure: 'DMW803T7RWE25ldhX73E/tqSWAZMaGUsd1dUbcxmXnU7OxpDPRSej2qtFJFHaYQi1inIL6zaKWD7Q5Mt6U5iueNvKtuDEabwjHw1Q2iwH/jLOKf0AtVvpQQJTBSIAzCDdqKTIwAnkFc5qRUuB1hphlrRhu7DVVZCVHZfuMIpAWI='

# starts xvfb on display port :99.0 (virtual Firefox)
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# install dependencies necessary to run this build
install:
  - npm install -g grunt-cli@0.1.x karma@0.10.x protractor@0.14.x
  - npm install --quiet

# configure Travis CI to Start Sauce Connect and start application
before_script:
  - curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
  - node app.js &
  - sleep 3 # give server some time to start

script:
  - grunt test:unit
  #- grunt protractor
  #- grunt test:e2e


# deploy app to Heroku
deploy:
  provider: heroku
  app: tweet-map
  api_key:
    -secure: 'ahPrWflfxAP1VEJf4Ud+4i4UHPof7fdu9It/hXddMSprzQEXU2+KHLr0VbHfVHmmndDyhGIqMtaZLt/IIb5sY2ffyPnP0md362W15o/FGQxlh4tzsgZ0NYkdnovNQNLoP716/GMIZlYgDZpm7C5OO+uGCq5lTya+h1suFaGopwM='

