language: node_js
node_js:
  - "0.10"

notifications:
  email:
    recipients:
      - martinmicunda@hotmail.com
    on_success: never
    on_failure: always

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g grunt-cli@0.1.x karma@0.10.x protractor@0.14.x
  - npm install --quiet
  - node app.js &
  - sleep 3 # give server some time to start

script:
  - grunt test:unit
  - grunt protractor
  - grunt test:e2e
